python app.py "dki jakarta" "kota jakarta barat"
python app.py "dki jakarta" "kota jakarta pusat"
python app.py "dki jakarta" "kota jakarta selatan"
python app.py "dki jakarta" "kota jakarta timur"
python app.py "dki jakarta" "kota jakarta utara"
python app.py "dki jakarta" "kab. kepulauan seribu"
python app.py "jawa barat" "kota bogor"
python app.py "jawa barat" "kota sukabumi"
python app.py "jawa barat" "kota bandung"
python app.py "jawa barat" "kota cirebon"
python app.py "jawa barat" "kota bekasi"
python app.py "jawa barat" "kota depok"
python app.py "jawa barat" "kota cimahi"
python app.py "jawa barat" "kota tasikmalaya"
python app.py "jawa barat" "kota banjar"
python app.py "jawa barat" "kab. bogor"
python app.py "jawa barat" "kab. sukabumi"
python app.py "jawa barat" "kab. cianjur"
python app.py "jawa barat" "kab. bandung"
python app.py "jawa barat" "kab. garut"
python app.py "jawa barat" "kab. tasikmalaya"
python app.py "jawa barat" "kab. ciamis"
python app.py "jawa barat" "kab. kuningan"
python app.py "jawa barat" "kab. cirebon"
python app.py "jawa barat" "kab. majalengka"
python app.py "jawa barat" "kab. sumedang"
python app.py "jawa barat" "kab. indramayu"
python app.py "jawa barat" "kab. subang"
python app.py "jawa barat" "kab. purwakarta"
python app.py "jawa barat" "kab. karawang"
python app.py "jawa barat" "kab. bekasi"
python app.py "jawa barat" "kab. bandung barat"
python app.py "jawa barat" "kab. pangandaran"
python app.py "sulawesi selatan" "kota makassar"
python app.py "sulawesi selatan" "kab. barru"
python app.py "sulawesi selatan" "kab. maros"
python app.py "sulawesi selatan" "kab. pangkajene kepulauan"
python app.py "sulawesi selatan" "kota pare pare"
python app.py "sulawesi tenggara" "kota bau bau"
python app.py "sulawesi tenggara" "kota kendari"
python app.py "sulawesi tenggara" "kab. wakatobi"
python combine.py "Activity_Location_List_LV4"
